from google.colab import drive
drive.mount('/content/drive')

"""#Run the library: PyPreprocessor_Lib

PyPreprocessor_Lib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1um7LbO0Dw8r_uxZrCeRW3ZOYesUruDCb
"""

from pypreprocessor_lib import DatasetPreprocessor
import pandas as pd

"""#Preprocessing of excel data - Numerical based data"""

df = pd.read_csv("/content/banana_quality.csv")
df.head(10)
print('Initial Shape of Data', df.shape)

preprocessor = DatasetPreprocessor('/content/banana_quality.csv')
preprocessed_data = preprocessor.preprocess(target_label='Quality')
preprocessed_data.head()

"""#Preprocessing of image data"""

path = '/content/google.jpeg'

preprocessor = DatasetPreprocessor(path)
preprocessed_data = preprocessor.preprocess()
preprocessed_data.shape

"""#Preprocessing of text data"""

df = pd.read_table("/content/My_old_man.txt", header=None, encoding='latin-1')
df.columns = ['Text']

preprocessor = DatasetPreprocessor('/content/My_old_man.txt')
preprocessed_data = preprocessor.preprocess()

print(preprocessed_data[:10])

#print(preprocessed_data[:1000])

"""*the data shown above is stored as an array. We will use join to put this as one single string.*"""

df_text = pd.DataFrame(preprocessed_data)
df_text_single = df_text.apply(lambda x: ' '.join(x.dropna().astype(str)), axis=1)
df_text_single.head(10)

"""#Preprocessing of excel data - Categorical data"""

df = pd.read_csv("/content/games.csv")
df.head(10)

preprocessor = DatasetPreprocessor("/content/games.csv")
preprocessed_data = preprocessor.preprocess(target_label='rating')
preprocessed_data.head()

preprocessor = DatasetPreprocessor("/content/Automobile.csv")
preprocessed_data = preprocessor.preprocess(target_label='mpg')
preprocessed_data.head()
